name: lol

on:
  workflow_run:
    workflows: ["Lint and Test"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Tests succeeded
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Tests failed LMAO
