name: PMD

on: [push, pull_request]

jobs:
  pmd-analyser-check:
    name: PMD Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd -d ./app -R ./pmd/codeStyle.xml -f text

# https://github.com/marketplace/actions/pmd-source-code-analyzer-action
# https://github.com/marketplace/actions/pmd-analyser
  
