name: PMD Static Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo implement PMD here

# https://github.com/marketplace/actions/pmd-source-code-analyzer-action
# https://github.com/marketplace/actions/pmd-analyser
  
