name: New Release

on:
  workflow_run:
    workflows: ["Expo Build"]
    types: [completed]

jobs:
  build-success:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ GITHUB_RUN_NUMBER }}
          release_name: Release ${{ GITHUB_RUN_NUMBER }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
  
  build-failed:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Build failed