name: TSLint
on: [push, pull_request]
jobs:
  tslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: Prepare
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install 
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: ./tslint/tslint.json
          project: ./app/**
          pattern: '*.ts{,x}'